version = 0.1

[default.deploy.parameters]
stack_name = "llm-security-api"
resolve_s3 = true
s3_prefix = "llm-security-api"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-west-1"
