# backend/template.yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: LLM Security Testing API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  SecurityTestAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            Auth:
              ApiKeyRequired: false

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: PromptRedTeamApiKey
      Description: API Key for PromptRedTeam
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: PromptRedTeamUsagePlan
      Description: Usage plan for PromptRedTeam API
      Throttle:
        BurstLimit: 100
        RateLimit: 50
      Quota:
        Limit: 10000
        Period: MONTH
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: Prod

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  ApiURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiKeyId:
    Description: "API Key ID"
    Value: !Ref ApiKey
