name: Deploy Backend API to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # Only run when backend code changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Build SAM application
        working-directory: ./backend
        run: sam build --use-container

      - name: Deploy to AWS Lambda
        working-directory: ./backend
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
